export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS';